#!/bin/bash

set -e

chown -R www-data:www-data /music
chown -R www-data:www-data /var/www/koel

# Change to program root directory.
cd /var/www/koel

# Run the next entrypoint in the chain.
echo "running docker-php-entrypoint with arguments $@"
docker-php-entrypoint $@
