#!/bin/bash

set -e

rsync -av --exclude 'public/img/covers/*' /tmp/koel/ /var/www/koel
# Change to program root directory.
cd /var/www/koel

# Run the next entrypoint in the chain.
echo "running docker-php-entrypoint with arguments $@"
docker-php-entrypoint $@
